/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include"main.h"

/*********************************************** end of Include files ************************************************/

/**********************************************************************************************************************
 * PRAGMAS
**********************************************************************************************************************/

/******************************************** end of PRAGMAs *********************************************************/

/**********************************************************************************************************************
 * Global Variables
**********************************************************************************************************************/
/* Variable declare for LED handler */
GPIO_Handle_t gpioLed ;


/*************************************** end of Global Variables ****************************************************/

/*********************************************************************************************************************
 * Static Function Prototypes
*********************************************************************************************************************/

/***************************************** end of Static Function Prototypes ****************************************/

/*********************************************************************************************************************
 * Function Definitions
*********************************************************************************************************************/

/*********************************************************************************************************************
* Function name      : void delay_us(uint32_t usec)
* Description        : This Function generates delay in micro seconds
*
*********************************************************************************************************************/
void delay_us(uint32_t usec)
{
    for(uint32_t i = 0; i < usec * 8; i++) {
        __asm__("nop");
    }
}
/*********************************************************************************************************************
* Function name      : void delay_ms(uint32_t msec)
* Description        : This Function generates delay in mili seconds
*
*********************************************************************************************************************/
void delay_ms(uint32_t msec)
{
	/* Loop 'msec' times */
	for(uint32_t i = 0; i < msec; i++) {
		/* Call delay_us(1000) to wait for 1000 microseconds (1 ms) */
		delay_us(1000);
	}
}
/*********************************************************************************************************************
* Function name      : int main(void)
* Description        : This Function is Initialize the gpio pin and toggle the LED
*
*********************************************************************************************************************/
int main(void)
{
	/*Configure GPIO pin : LED */
	gpioLed.pGPIOx = GPIOA;
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	gpioLed.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	/* Function call to enable Peripheral clock */
	GPIO_PeriClockControl(GPIOA, ENABLE);
	/* Initialize all configured peripherals */
	/* Function call to Initialize GPIO Pin */
	GPIO_Init(&gpioLed);
	/* Infinite loop */
	while(1U)
	{
		/* Function call to Toggle LED */
		GPIO_TogglePin(GPIOA, GPIO_PIN_NO_5);
		/* Function Call to Generate Delay */
		delay_ms(10);
	}

}
