/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**********************************************************************************************************************
 * Include files
**********************************************************************************************************************/
#include"main.h"

/*********************************************** end of Include files ************************************************/

/**********************************************************************************************************************
 * PRAGMAS
**********************************************************************************************************************/

/******************************************** end of PRAGMAs *********************************************************/

/**********************************************************************************************************************
 * Global Variables
**********************************************************************************************************************/
/* Flags used to indicate updated data is received*/


/*************************************** end of Global Variables ****************************************************/

/*********************************************************************************************************************
 * Static Function Prototypes
*********************************************************************************************************************/

/***************************************** end of Static Function Prototypes ****************************************/

/*********************************************************************************************************************
 * Function Definitions
*********************************************************************************************************************/

/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
void delay_us(uint32_t usec)
{
    for(uint32_t i = 0; i < usec * 8; i++) {
        __asm__("nop");
    }
}
/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
void delay_ms(uint32_t msec)
{
    for(uint32_t i = 0; i < msec; i++) {
        delay_us(1000);
    }
}
/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
int main(void)
{

	GPIO_Handle_t gpioLed ={0} ;
	GPIO_Handle_t gpioSwitch ={0};


	gpioSwitch.pGPIOx = GPIOC;
	gpioSwitch.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	gpioSwitch.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_IT_FI;
	gpioSwitch.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioSwitch.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;



	gpioLed.pGPIOx = GPIOA;
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	gpioLed.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&gpioSwitch);
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&gpioLed);

	GPIO_IRQProrityConfig(IRQ_NO_EXTI15_10,NVIC_IRQ_PRI15);
	GPIO_IRQITConfig(IRQ_NO_EXTI15_10, ENABLE);


	while(1U)
	{

	}

}
/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandler(GPIO_PIN_NO_13);
	GPIO_TogglePin(GPIOA, GPIO_PIN_NO_5);
	delay_ms(10);
}
/************************************************ end of main.c ***************************************************/
